runtime: go116

handlers:
- url: /.*
  script: main.go
  #secure: always  
  #login: admin
#- url: /books/.*
  #script: auto
  #secure: always  
#- url: /books/show/.*
  #script: auto
  #secure: always  
#- url: /books/create/.*
  #script: auto
  #secure: always  
#- url: /books/update/.*
  #script: auto
  #secure: always    
#- url: /books/update/process.*
  #script: auto
  #secure: always    
#- url: /books/create/process.*
 #script: auto
 #secure: always    
#- url: /books/delete/process.*
  #script: auto
  #secure: always    
